version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
    - echo "Logging in to Amazon ECR..."
    - aws --version
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <account_id>.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
    - echo "Build started on $(date)"
    - npm install
    - echo "Building the Docker image..."
    - docker build -t <image_repo_name> .
    - docker images
    - echo "Tagging the Docker image..."
    - docker tag <image_repo_name>:latest <account_id>.dkr.ecr.us-east-1.amazonaws.com/<image_repo_name>:<CODEBUILD_RESOLVED_SOURCE_VERSION>

  post_build:
    commands:
    - echo "Build completed on $(date)"
    - echo "OK"
    - echo "Pushing the Docker image..."
    - docker push <account_id>.dkr.ecr.us-east-1.amazonaws.com/<image_repo_name>:<CODEBUILD_RESOLVED_SOURCE_VERSION>

artifacts:
  files: imagedefinitions.json
